**Google classroom code: ejjak4q**
--





# Numpy Module
NumPy, stands from 'Numeric Python" or "Numerical Python" and is very important library for scientific computing in Python.

It has large variety of functions that can be used to solved problems in Science and Engineering.

For data Science, it is one of the important packages used for data science as it provides the array data structure.


> Arrays are superior to Python lists as it is more compact, convenient, and efficient.

> Provides faster access in reading and writing items.

Another Important tool of Numpy is high performance multidimensional arrays,
>>which are powerful data structure for efficient computation of arrays and matrices.

>> provides a large number of high-level matehmatical functions.

> Numpy is a cummonity-driven open source project  and is written partially in Python, but most of the parts that require fast computation are written in C++.
>> This tell that C++ is important, if one has to create library

[Numpy Project](https://pypi.org/project/numpy/)







# Remember the following points
First import it
> import numpy as np

Numpy is mainly used for creating **homogeneous multidimensional arrays**

In Numpy, dimensions are called axes
e.g. Array for coordinated of a point in 3D space [1,2,3] has one axis. That axis has 3 elements in it.

[[1,1,2],[2,3,1]] has 2 axes.


#Creating numpy arrays

There are several ways to create an array in NumPy. Each one them provide some flexibility

**np.array** allows users to create an array of elements

In [ ]:
import numpy as np
A = np.array([10,20,30,40,50])
B = np.array((50,60,80,90,100))
print(A)
print(B)

[10 20 30 40 50]
[ 50  60  80  90 100]


A is an array of a list of integers

B is an array of a tuple of integers

**np.arange** takes **start, end** of a range and the **interval** arguments to return a one-dimensional array with evenly spaced elements from the interval specified by the value of start and end in gap of steps

**np.array(start, stop, step, dtype=None)**

In [ ]:
A = np.arange(6,100,3)
print(A)

[ 6  9 12 15 18 21 24 27 30 33 36 39 42 45 48 51 54 57 60 63 66 69 72 75
 78 81 84 87 90 93 96 99]


In [ ]:
A = np.arange(6,100,3, dtype=float)
print(A)

[ 6.  9. 12. 15. 18. 21. 24. 27. 30. 33. 36. 39. 42. 45. 48. 51. 54. 57.
 60. 63. 66. 69. 72. 75. 78. 81. 84. 87. 90. 93. 96. 99.]


**np.linspace** takes **start,end** and the **number of the elements ** to be created as arguments and returns a one-dimensional array that has evenly spaced numbers over the specified interval.

**np.linspace(start, stop, num, endpoint=True, retstep=False, dtype=None)**

In [ ]:
A = np.linspace(10,50,80, dtype=int)
print(A)

[10 10 11 11 12 12 13 13 14 14 15 15 16 16 17 17 18 18 19 19 20 20 21 21
 22 22 23 23 24 24 25 25 26 26 27 27 28 28 29 29 30 30 31 31 32 32 33 33
 34 34 35 35 36 36 37 37 38 38 39 39 40 40 41 41 42 42 43 43 44 44 45 45
 46 46 47 47 48 48 49 50]


In [ ]:
A = np.linspace(10,50,80, endpoint=False, dtype=int)
print(A)

[10 10 11 11 12 12 13 13 14 14 15 15 16 16 17 17 18 18 19 19 20 20 21 21
 22 22 23 23 24 24 25 25 26 26 27 27 28 28 29 29 30 30 31 31 32 32 33 33
 34 34 35 35 36 36 37 37 38 38 39 39 40 40 41 41 42 42 43 43 44 44 45 45
 46 46 47 47 48 48 49 49]


In [ ]:
A = np.linspace(10,50,80, endpoint=True, retstep=True, dtype=int)
print(A)

(array([10, 10, 11, 11, 12, 12, 13, 13, 14, 14, 15, 15, 16, 16, 17, 17, 18,
       18, 19, 19, 20, 20, 21, 21, 22, 22, 23, 23, 24, 24, 25, 25, 26, 26,
       27, 27, 28, 28, 29, 29, 30, 30, 31, 31, 32, 32, 33, 33, 34, 34, 35,
       35, 36, 36, 37, 37, 38, 38, 39, 39, 40, 40, 41, 41, 42, 42, 43, 43,
       44, 44, 45, 45, 46, 46, 47, 47, 48, 48, 49, 50]), np.float64(0.5063291139240507))


In [ ]:
A, step = np.linspace(0, 10, 5, retstep=True)
print(A)
print(step)

[ 0.   2.5  5.   7.5 10. ]
2.5


In [ ]:
A, step = np.linspace(0, 10, 5, dtype=int, retstep=True)
print(A)
print(step)

[ 0  2  5  7 10]
2.5


**Create Numpy array from list**

Python list having elements enclosed between square brackets can be converted into a NumPy array by using array() method

In [ ]:
A=[11,12,13,14,15,16,17,18,19,20,21,12,13,14,15,16] # List
print(A)
myArray = np.array(A)
print("Numpy array created using List is", myArray)

[11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 12, 13, 14, 15, 16]
Numpy array created using List is [11 12 13 14 15 16 17 18 19 20 21 12 13 14 15 16]


**Create Numpy array from Tuple**

In [ ]:
A=(1,2,3,4,5,6,7,8,9,10,11,12,13) # Tuple
print(A)
myArray = np.array(A)
print("Array created from tuple ", myArray)

(1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13)
Array created from tuple  [ 1  2  3  4  5  6  7  8  9 10 11 12 13]


#What is difference between List and Tuple

**List**  is of an ordered collection data type that is mutable which means it can be easily modified and we can change its data values and a list can be indexed, sliced, and changed and each element can be accessed using its index value in the list.

**Tuple**   is an ordered and an immutable data type which means we cannot change its values and tuples are written in round brackets.

NumPy  allow us to create "empty" arrays that are placeholders for values and can be filled up later.

One can also create arrays and initialize them with ones or zeros or create arrays and initialize them with ones or zeros or create arrays that get filled up with evenly spaced values.

Example of List


In [ ]:
# Create the list
my_list = [1, 3, 4, 5, 124, 1241, 5223, 5241, 52425, 1234, 1413, 552, 5662, 3345, 11345, 12341]
print("Original list (first 5 elements):",my_list[0:5])

# 1. Change an element
# Let's change the 3rd element (at index 2) from 4 to 99
my_list[2] = 99

# 2. Add an element to the end
my_list.append(777)

# 3. Remove an element
my_list.remove(5) # Removes the first occurrence of the number 5

print("Modified list (first 5 elements): ", my_list[0:5])
print("The last element is now: ", my_list[-1])

Original list (first 5 elements): [1, 3, 4, 5, 124]
Modified list (first 5 elements):  [1, 3, 99, 124, 1241]
The last element is now:  777


Example of Tuple

In [ ]:
# Create the tuple
my_tuple = (1, 3, 4, 5, 124, 1241, 5223, 5241, 52425, 1234, 1413, 552, 5662, 3345, 11345, 12341)
print("Original tuple (first 5 elements): ", my_tuple[0:5])
# Let's try to change the 3rd element (at index 2)
my_tuple[2] = 99

Original tuple (first 5 elements):  (1, 3, 4, 5, 124)


TypeError: 'tuple' object does not support item assignment

In [ ]:
# Create the tuple
my_tuple = (1, 3, 4, 5, 124, 1241, 5223, 5241, 52425, 1234, 1413, 552, 5662, 3345, 11345, 12341)
print("Original tuple (first 5 elements): ", my_tuple[0:5])

# Let's try to change the 3rd element (at index 2)
try:
    my_tuple[2] = 99
except TypeError as e:
    print("\nError in my code is :",  {e})

Original tuple (first 5 elements):  (1, 3, 4, 5, 124)

Error in my code is : {TypeError("'tuple' object does not support item assignment")}


 Python list is highly flexible and can hold elements of different data types.

 A NumPy ndarray, however, requires all elements to be of the same data type for performance reasons.

In [ ]:
 #A Python list can hold different data types
py_list = [1, "hello", 3.0, True]
print("Python List: ", py_list)
print("Type: ", type(py_list))

# A NumPy array has a single, uniform data type
np_array = np.array([1, 2, 3, 4])
print("NumPy Array: ", np_array)
print("Type: ", type(np_array))
print("Data Type (dtype):",  np_array.dtype)

Python List:  [1, 'hello', 3.0, True]
Type:  <class 'list'>
NumPy Array:  [1 2 3 4]
Type:  <class 'numpy.ndarray'>
Data Type (dtype): int64


NumPy arrays allow for vectorized operations, meaning you can perform mathematical operations on the entire array at once without writing an explicit for loop.

This is significantly faster than performing the same operation on a list.  

Let's see this

In [ ]:
%%timeit -n 10 -r 5

# We must use a loop or list comprehension
large_list = range(1000000)
result_list = [x + 10 for x in large_list]

65.7 ms ± 3.56 ms per loop (mean ± std. dev. of 5 runs, 10 loops each)


NOw using NumPPy ndarry

In [ ]:
%%timeit -n 10 -r 5

# We can add 10 directly to the array
large_array = np.arange(1000000)
result_array = large_array + 2

3.93 ms ± 303 µs per loop (mean ± std. dev. of 5 runs, 10 loops each)


NumPy arrays are also more memory-efficient than Python lists.

 An ndarray stores its elements in one continuous block of memory, whereas a list stores pointers to objects scattered across memory.

In [ ]:
import sys
# Create a list and an array with 1000 elements
num_elements = 1000
py_list = list(range(num_elements))
np_array = np.arange(num_elements)

# Get the size in bytes
list_size = sys.getsizeof(1) * len(py_list)
array_size = np_array.nbytes # .nbytes gives the total bytes of the array's elements

print("Memory used by Python List: " , list_size, " bytes")
print("Memory used by NumPy Array: ", array_size, " bytes")

Memory used by Python List:  28000  bytes
Memory used by NumPy Array:  8000  bytes


#Functions for creating Numpy Array

**np.ones** creates a list, tuple or matrix of specified data types and shape (or size) filled with ones

In [ ]:
A= np.ones(6,dtype=np.double)
print(A)

[1. 1. 1. 1. 1. 1.]


In [ ]:
A= np.ones((6,9),dtype=np.double) # 6 rows and 9 columns
print(A)

[[1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1.]]


**np.ones** creates a matrix of specified data type and shape filled with zeros

In [ ]:
A=np.zeros((6,9), dtype=np.int16) # 6 rows and 9 columns
print(A)

[[0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]]


**np.full** create an array with specified size and type and fills a specified value


In [ ]:
A=np.full((6,9),5.6789) # 6 rows and 9 columns
print(A)

[[5.6789 5.6789 5.6789 5.6789 5.6789 5.6789 5.6789 5.6789 5.6789]
 [5.6789 5.6789 5.6789 5.6789 5.6789 5.6789 5.6789 5.6789 5.6789]
 [5.6789 5.6789 5.6789 5.6789 5.6789 5.6789 5.6789 5.6789 5.6789]
 [5.6789 5.6789 5.6789 5.6789 5.6789 5.6789 5.6789 5.6789 5.6789]
 [5.6789 5.6789 5.6789 5.6789 5.6789 5.6789 5.6789 5.6789 5.6789]
 [5.6789 5.6789 5.6789 5.6789 5.6789 5.6789 5.6789 5.6789 5.6789]]


**np.random.rand** creates array with specified size and fill random values

In [ ]:
A=np.random.rand(6,4)
print(A)
# Now how to get integer




[[0.73456964 0.763101   0.6508285  0.63089524]
 [0.31751366 0.24025308 0.1157515  0.34751865]
 [0.05433773 0.22452627 0.59854614 0.31456087]
 [0.29925309 0.26040464 0.61505206 0.31522113]
 [0.79829324 0.39277894 0.52913455 0.18329277]
 [0.19397783 0.15039496 0.78681892 0.92787071]]


In [ ]:
B=np.random.rand(3,4,2)
print(B)

[[[0.25256732 0.84423459]
  [0.55246777 0.76920072]
  [0.83727312 0.09677822]
  [0.1135161  0.2620803 ]]

 [[0.73920202 0.27961315]
  [0.68872788 0.54049363]
  [0.53336091 0.59887949]
  [0.4737216  0.97087298]]

 [[0.19830244 0.05349054]
  [0.37501271 0.42829889]
  [0.93122782 0.41225369]
  [0.98093474 0.10696198]]]


**np.random.randint** creates array wit integer, has options *low*, *high*, *size*

In [ ]:
Ai= np.random.randint(0,5,size=(6,4))
print(Ai)
B=np.random.randint(low=0,high=10,size=(3,6))
print(B)
B2=np.random.randint(low=0,high=10,size=(3,6,2))
print(B2)

[[0 4 1 0]
 [1 4 4 1]
 [4 1 4 2]
 [4 1 3 0]
 [0 3 3 4]
 [4 2 0 3]]
[[0 9 1 3 8 1]
 [2 6 7 8 3 3]
 [3 5 5 8 1 6]]
[[[6 2]
  [8 4]
  [2 1]
  [6 6]
  [4 9]
  [5 9]]

 [[8 4]
  [2 6]
  [9 4]
  [9 0]
  [6 7]
  [3 6]]

 [[0 2]
  [5 0]
  [0 6]
  [5 5]
  [6 8]
  [7 5]]]


**np.empty** returns a new array of given shape and type with empty values

In [ ]:
A= np.empty((3,6))
print(A)

[[2.87e-322 3.01e-322 7.91e-323 1.33e-322 1.78e-322 3.80e-322]
 [2.67e-322 2.37e-322 4.40e-322 3.71e-322 2.47e-322 4.84e-322]
 [1.98e-323 3.85e-322 1.04e-322 1.93e-322 4.94e-324 4.74e-322]]


# numpy.lookfor() method

One can get the information about the module in the numpy by using
```
numpy.lookfor()
```
[More details](https://numpy.org/doc/1.26/reference/generated/numpy.lookfor.html)

This has been discontinued from Numpy 2.0
Now, one can do an external search of official documentation





In [ ]:
print(np.lookfor("isdigit"))

Numpy one can get  information about the function, class, or module with the help of
```
numpy.info().
```
This will return the help information for a function, class, or module.

In [ ]:
print(np.info("mean"))

     *** Found in numpy ***
Compute the arithmetic mean along the specified axis.

Returns the average of the array elements.  The average is taken over
the flattened array by default, otherwise over the specified axis.
`float64` intermediate and return values are used for integer inputs.

Parameters
----------
a : array_like
    Array containing numbers whose mean is desired. If `a` is not an
    array, a conversion is attempted.
axis : None or int or tuple of ints, optional
    Axis or axes along which the means are computed. The default is to
    compute the mean of the flattened array.

    .. versionadded:: 1.7.0

    If this is a tuple of ints, a mean is performed over multiple axes,
    instead of a single axis or all the axes as before.
dtype : data-type, optional
    Type to use in computing the mean.  For integer inputs, the default
    is `float64`; for floating point inputs, it is the same as the
    input dtype.
out : ndarray, optional
    Alternate output array in which t



---



# Array Attributes

Some important attributes of NumPy are :

**Ndim** displays the dimension of the array

**Shape** indicate the size of the array

**Size** gives the total number o elements in the array

**Dtype** return type of the elements in the array

**Itemsize** size of the bytes of each item

**Reshape** this will reshapes the *array*

In [ ]:
B=np.random.randint(low=0,high=10,size=(3,6))
print(B)
print('number of the dimensions in B', np.ndim(B))
print('Shape of B', np.shape(B))
print('Size of B', np.size(B))
print('Dtype of B', B.dtype)
print('Item size of B ', B.itemsize , ' bytes')

[[1 2 2 6 9 1]
 [2 9 0 8 4 4]
 [8 4 7 8 1 7]]
number of the dimensions in B 2
Shape of B (3, 6)
Size of B 18
Dtype of B int64
Item size of B  8  bytes


One can reshape the Array.  From 2 D, one can get 1D

Useful in many places

In [ ]:

NewB = B.reshape(1,18)
print(NewB)
print('number of the dimensions in NewB  ', np.ndim(NewB))
print('Shape of NewB ', np.shape(NewB))

[[1 2 2 6 9 1 2 9 0 8 4 4 8 4 7 8 1 7]]
number of the dimensions in NewB   2
Shape of NewB  (1, 18)


#Converting 2D numpy arrays into 1 D array
 Three ways to do so.

 **np.flatten()**

 **np.ravel()**

 **np.reshape()**


In [ ]:
A = np.random.randint(low=0,high=100,size=(3,6))
print(A)
B= A.flatten()
print(" \nUsing Flatten")
print(B)

D=A.flatten(order='F')  #column first
print(" \nUsing flatten with order F which means column first")
print(D)

D=A.flatten(order='C')  # row
print(" \nUsing flatten with order C which means row first")
print(D)

print(" \nUsing flatten with order K which it flatten the array in same order in which elements occurred in the memory")
D=A.flatten(order='K') # memory
print(D)

print(A)

[[38 86 95 25 21 95]
 [38 55 19 58  4 19]
 [30  3 80 44 78  1]]
 
Using Flatten
[38 86 95 25 21 95 38 55 19 58  4 19 30  3 80 44 78  1]
 
Using flatten with order F which means column first
[38 38 30 86 55  3 95 19 80 25 58 44 21  4 78 95 19  1]
 
Using flatten with order C which means row first
[38 86 95 25 21 95 38 55 19 58  4 19 30  3 80 44 78  1]
 
Using flatten with order K which it flatten the array in same order in which elements occurred in the memory
[38 86 95 25 21 95 38 55 19 58  4 19 30  3 80 44 78  1]
[[38 86 95 25 21 95]
 [38 55 19 58  4 19]
 [30  3 80 44 78  1]]


**np.ravel()**

In [ ]:
print(A)
C = A.ravel()
print(" \nUsing Ravel")
print(C)

D=A.ravel(order='F')  #column first
print(" \nUsing Ravel with order F which means column first")
print(D)

D=A.ravel(order='C')  # row
print(" \nUsing Ravel with order C which means row first")
print(D)

print(" \nUsing Ravel with order K which it flatten the array in same order in which elements occurred in the memory")
D=A.ravel(order='K') # memeory
print(D)



[[38 86 95 25 21 95]
 [38 55 19 58  4 19]
 [30  3 80 44 78  1]]
 
Using Ravel
[38 86 95 25 21 95 38 55 19 58  4 19 30  3 80 44 78  1]
 
Using Ravel with order F which means column first
[38 38 30 86 55  3 95 19 80 25 58 44 21  4 78 95 19  1]
 
Using Ravel with order C which means row first
[38 86 95 25 21 95 38 55 19 58  4 19 30  3 80 44 78  1]
 
Using Ravel with order K which it flatten the array in same order in which elements occurred in the memory
[38 86 95 25 21 95 38 55 19 58  4 19 30  3 80 44 78  1]


What is difference between flatten and ravel

Main difference is that flatten always returns a new copy of the array, while ravel returns a view of the original array whenever possible.

Changes made to the array returned by ravel might affect the original array, while changes to the one from flatten will not.

In [ ]:
import numpy as np

# Create our original 2D array
a = np.array([[1, 2, 3],
              [4, 5, 6]])

print(f"Original array:\n{a}\n")

# --- Using flatten (makes a copy) ---
f = a.flatten()
f[0] = 99  # Change the first element of the flattened array
print("After modifying the 'flattened' array...")
print(f"Flattened array: {f}")
print(f"Original array is UNCHANGED:\n{a}\n")


# --- Using ravel (makes a view) ---
r = a.ravel()
r[0] = 77  # Change the first element of the raveled array
print("After modifying the 'raveled' array...")
print(f"Raveled array:   {r}")
print(f"Original array IS CHANGED:\n{a}")

Original array:
[[1 2 3]
 [4 5 6]]

After modifying the 'flattened' array...
Flattened array: [99  2  3  4  5  6]
Original array is UNCHANGED:
[[1 2 3]
 [4 5 6]]

After modifying the 'raveled' array...
Raveled array:   [77  2  3  4  5  6]
Original array IS CHANGED:
[[77  2  3]
 [ 4  5  6]]


**np.reshape()**

syntax is

```
numpy.reshape(a, newshape, order='C')

```


    order='C' (C-style): Reads elements by going across the rows first. This is the default.

    order='F' (Fortran-style): Reads elements by going down the columns first.






In [ ]:
print(A)
print('Shape of A', np.shape(A),'\n')

print('\n We reshape the A into 2 x 9')
D=A.reshape(2,9)

print(D,'\n')

print('\n We reshape the A into 2 x 9 with order F')
D=A.reshape(2,9, order='F')

print(D,'\n')

print('\n We reshape the A into 1 x 9')
D=A.reshape(1,18)
print(D)
D=A.reshape(1,18, order='F')
print( '\n We reshape the A into 1 x 9 \n with order F ')
print(D ,'\n')

# One could pass -1 as value in the reshape() to convert a 2D into 1 D array
D=A.reshape(-1)
print(D,'\n')

D=A.reshape(18,1)
print(D)

[[38 86 95 25 21 95]
 [38 55 19 58  4 19]
 [30  3 80 44 78  1]]
Shape of A (3, 6) 


 We reshape the A into 2 x 9
[[38 86 95 25 21 95 38 55 19]
 [58  4 19 30  3 80 44 78  1]] 


 We reshape the A into 2 x 9 with order F
[[38 30 55 95 80 58 21 78 19]
 [38 86  3 19 25 44  4 95  1]] 


 We reshape the A into 1 x 9
[[38 86 95 25 21 95 38 55 19 58  4 19 30  3 80 44 78  1]]

 We reshape the A into 1 x 9 
 with order F 
[[38 38 30 86 55  3 95 19 80 25 58 44 21  4 78 95 19  1]] 

[38 86 95 25 21 95 38 55 19 58  4 19 30  3 80 44 78  1] 

[[38]
 [86]
 [95]
 [25]
 [21]
 [95]
 [38]
 [55]
 [19]
 [58]
 [ 4]
 [19]
 [30]
 [ 3]
 [80]
 [44]
 [78]
 [ 1]]


# Array Slicing
Slicing an array is important when we have to analyze some array elements or take sample of data.

As we use square brackets to access individual array elements. Same brackets are used to access subarrays with slice notration, marked by the colon **(:)** character

**Arr[2:8]** prints element from index 2 to 8. Please remember index in array start from 0

**Arr[2::3]** print every 3rd element from index 2 to the end

**Arr[::-1]** print array in the reverse order

**Arr[5:]** print from index 5 to the end

[More ideas
](https://www.earthdatascience.org/courses/intro-to-earth-data-science/scientific-data-structures-python/numpy-arrays/indexing-slicing-numpy-arrays/)

In [ ]:
A = np.random.randint(low=0,high=100,size=(6,6))
print(A)
print("\nArr[2:4] = \n", A[2:4])
print("\n\nArr[3:5] = \n", A[3:5])

[[27 46 54 93 33 79]
 [57 55 26 24 17 89]
 [41 25  5 20 47 82]
 [35 93 86 42 77 56]
 [19 58  7 25 17 87]
 [53 96  5 55 63 26]]

Arr[2:4] = 
 [[41 25  5 20 47 82]
 [35 93 86 42 77 56]]


Arr[3:5] = 
 [[35 93 86 42 77 56]
 [19 58  7 25 17 87]]


Always give one less, always remember

Arr[2::3] print every 3rd element from index 2 to the end

In [ ]:
A = np.random.randint(low=0,high=100,size=(6,6))
print(A)
print("\n Arr[1::2] = \n", A[1::2])

print("\n Arr[1::3] = \n", A[1::3])

[[ 5 44 92 65 40  3]
 [95 14 82 96 83 65]
 [72 56 68 56  8 81]
 [58 95 27 78  9 95]
 [13 48  7 37 80 45]
 [71 42 34 20 70 25]]

 Arr[1::2] = 
 [[95 14 82 96 83 65]
 [58 95 27 78  9 95]
 [71 42 34 20 70 25]]

 Arr[1::3] = 
 [[95 14 82 96 83 65]
 [13 48  7 37 80 45]]



Below will print the array in the reverse order



In [ ]:
A = np.random.randint(low=0,high=100,size=(6,6))
print(A)
print("\n Arr[::-1] = \n", A[::-1])

[[15 26 34 87 61 86]
 [20 39  0 16 37 55]
 [43 15 40  5 71 26]
 [83 12 80 89 57 89]
 [35 42 21 15 35 56]
 [ 9 65 99 88 82 16]]

 Arr[::-1] = 
 [[ 9 65 99 88 82 16]
 [35 42 21 15 35 56]
 [83 12 80 89 57 89]
 [43 15 40  5 71 26]
 [20 39  0 16 37 55]
 [15 26 34 87 61 86]]


In [ ]:
A = np.random.randint(low=0,high=100,size=(6,6))
print(A)
print("\n Arr[::-2] = \n", A[::-2])

[[61 66 39 81 55 96]
 [10 60 76 89 45 44]
 [40 90 36 77 81 34]
 [27 85 59 42 72 47]
 [90 70 90 74 42 96]
 [50  9 27 93 16 42]]

 Arr[::-2] = 
 [[50  9 27 93 16 42]
 [27 85 59 42 72 47]
 [10 60 76 89 45 44]]


In [ ]:
A = np.random.randint(low=0,high=100,size=(6,6))
print(A)
print("\nArr[::-3] = \n", A[::-3])

[[32 52 84 84 25 17]
 [93 14 50 65 89 24]
 [22 57 32 18 71 41]
 [ 1 51 90 59 81 42]
 [37 16  7 98 26 18]
 [59 72  1 96 57 91]]

Arr[::-3] = 
 [[59 72  1 96 57 91]
 [22 57 32 18 71 41]]


In [ ]:
A = np.random.randint(low=0,high=100,size=(6,6))
print(A)
print("\nArr[-1::] = \n", A[-1::])

[[82 48 69 44 48  9]
 [99 45 97 14 74 78]
 [76 23 87 22 86 34]
 [11  3 37 30 48 77]
 [30 95 48 56 53 26]
 [54 93  8 96 48 23]]

Arr[-1::] = 
 [[54 93  8 96 48 23]]


In [ ]:
A = np.random.randint(low=0,high=100,size=(6,6))
print(A)
print("\nArr[-2::] = \n", A[-2::])

[[73 96 97 45 87 24]
 [85 28 44 33 95 64]
 [43 60 20 76 10 72]
 [70 60 93 73 51 77]
 [71 55 69 11 17 82]
 [ 2 33 54  2 60 54]]

Arr[-2::] = 
 [[71 55 69 11 17 82]
 [ 2 33 54  2 60 54]]


In [ ]:
A = np.random.randint(low=0,high=100,size=(6,6))
print(A)
print("\nArr[2:] = \n", A[2:])

[[87 22 96 26 17 42]
 [37 37 90 49 42 83]
 [46 23 19 93 24 91]
 [50  4 98 17 89  5]
 [35 46 24 47  3 59]
 [51 76 55 83 96 46]]

Arr[2:] = 
 [[46 23 19 93 24 91]
 [50  4 98 17 89  5]
 [35 46 24 47  3 59]
 [51 76 55 83 96 46]]


In [ ]:
A = np.random.randint(low=0,high=100,size=(6,6))
print(A)
D=A[:2]
print("\nArr[:2] = \n", D)

[[44 14 98 60 93 43]
 [60 57 18  2 56  7]
 [71 38 76 89 84 98]
 [25 71 82 67 48 73]
 [ 6  3 62 51 84 61]
 [87 68 93 27 42 26]]

Arr[:2] = 
 [[44 14 98 60 93 43]
 [60 57 18  2 56  7]]


**Now, if one simply want a particular column then**

In [ ]:
A = np.random.randint(low=0,high=100,size=(6,6))
print(A)
D=A[:,2]
print("\nArr[:,2] = \n", D)

[[12 50 45 35 80 85]
 [ 2 32 95 43 69 29]
 [ 1 50 68 37 27 68]
 [88 13 45 82 29 98]
 [86 77 16 72 86 24]
 [75  9  5 98 78 24]]

Arr[:,2] = 
 [45 95 68 45 16  5]


In [ ]:
A = np.random.randint(low=0,high=100,size=(6,6))
print(A)
D=A[:,2:]
print("\nArr[:,2:] = \n", D)

[[ 2 87  0 62 83 43]
 [ 3 27  4 41 69 26]
 [29 15 49 81 58 88]
 [ 7 24 62 72 93 31]
 [69 93 87 73 19  7]
 [87 98 74 54 24 43]]

Arr[:,2:] = 
 [[ 0 62 83 43]
 [ 4 41 69 26]
 [49 81 58 88]
 [62 72 93 31]
 [87 73 19  7]
 [74 54 24 43]]


In [ ]:

print(A)
D=A[:,2:5]
print("\nArr[:,2:5] = \n", D)

[[ 2 87  0 62 83 43]
 [ 3 27  4 41 69 26]
 [29 15 49 81 58 88]
 [ 7 24 62 72 93 31]
 [69 93 87 73 19  7]
 [87 98 74 54 24 43]]

Arr[:,2:5] = 
 [[ 0 62 83]
 [ 4 41 69]
 [49 81 58]
 [62 72 93]
 [87 73 19]
 [74 54 24]]


When we create array slices, views from the array are returned rather than copies of the array data.

This is a major difference between python list and numpy array.

In [ ]:
A = np.random.randint(low=0,high=100,size=(6,6))
print('Original A \n',A)

Sub_A = A[2:]

print('\n sub_A \n', Sub_A)

Sub_A[3,3]=999
Sub_A[3,4]=999
Sub_A[3,5]=999
print('\n Modified sub_A \n', Sub_A)
print('Now the Original A also get modified \n',A)



Original A 
 [[46 38 92 24 16 70]
 [26 23  3  5 17 98]
 [87 23 24 98  1 72]
 [43 36 60 80  9 69]
 [51 20 94  2 32 51]
 [42 52 63  4 84 73]]

 sub_A 
 [[87 23 24 98  1 72]
 [43 36 60 80  9 69]
 [51 20 94  2 32 51]
 [42 52 63  4 84 73]]

 Modified sub_A 
 [[ 87  23  24  98   1  72]
 [ 43  36  60  80   9  69]
 [ 51  20  94   2  32  51]
 [ 42  52  63 999 999 999]]
Now the Original A also get modified 
 [[ 46  38  92  24  16  70]
 [ 26  23   3   5  17  98]
 [ 87  23  24  98   1  72]
 [ 43  36  60  80   9  69]
 [ 51  20  94   2  32  51]
 [ 42  52  63 999 999 999]]


This seems harmful, but this feature of NumPy array is imporant, especially when we are dealing with large amount of data.

We don't need to create mutiple copies. Remember the good coder is the one who understand the limitation of memory.  One should respect the RAM and also the disk space.

Still sometime one dont want to modify the original Data, then simply create copy of the array

**Creating copy of the arrays**

If one need to create copy then, one has to use **copy()**

In [ ]:
A = np.random.randint(low=0,high=100,size=(6,6))
print('Original A \n',A)

Sub_A = A[2:].copy()

print('\n sub_A \n', Sub_A)

Sub_A[3,3]=999
Sub_A[3,4]=999
Sub_A[3,5]=999
print('\n Modified sub_A \n', Sub_A)
print('Now the Original A also get modified \n',A)

Original A 
 [[97 19 21 91 50 31]
 [39 58 10 70 78 60]
 [80 92 65 85 98 31]
 [96 89 11 52  6 11]
 [16 82 74 44 12 83]
 [42 55 18 75 42 13]]

 sub_A 
 [[80 92 65 85 98 31]
 [96 89 11 52  6 11]
 [16 82 74 44 12 83]
 [42 55 18 75 42 13]]

 Modified sub_A 
 [[ 80  92  65  85  98  31]
 [ 96  89  11  52   6  11]
 [ 16  82  74  44  12  83]
 [ 42  55  18 999 999 999]]
Now the Original A also get modified 
 [[97 19 21 91 50 31]
 [39 58 10 70 78 60]
 [80 92 65 85 98 31]
 [96 89 11 52  6 11]
 [16 82 74 44 12 83]
 [42 55 18 75 42 13]]


**Reshaping of arrays**

Reshaping array change the shape of an array.

This is done by adding or removing the dimensions or changing the nmber of elements in each dimensions.

It is reshaped by **reshape()**

In [ ]:
twoD_A = np.random.randint(low=0,high=100,size=(6,6))
print('two dimensional A \n',twoD_A)
oneD_A  = twoD_A.reshape(1,36)
print('One dimensional A \n',oneD_A)
twoD_Aa  = oneD_A.reshape(3,12)
print('two dimensional Aa \n',twoD_Aa)
threeD_A = oneD_A.reshape(2,6,3)
print('three dimensional Aa \n',threeD_A)

two dimensional A 
 [[21 68 40 51 85 82]
 [80 62 32 69 76 51]
 [59  9 42 23 75 44]
 [22  1 80 12 84 26]
 [19 10 90 37 78 28]
 [87 61 71 33 63 13]]
One dimensional A 
 [[21 68 40 51 85 82 80 62 32 69 76 51 59  9 42 23 75 44 22  1 80 12 84 26
  19 10 90 37 78 28 87 61 71 33 63 13]]
two dimensional Aa 
 [[21 68 40 51 85 82 80 62 32 69 76 51]
 [59  9 42 23 75 44 22  1 80 12 84 26]
 [19 10 90 37 78 28 87 61 71 33 63 13]]
three dimensional Aa 
 [[[21 68 40]
  [51 85 82]
  [80 62 32]
  [69 76 51]
  [59  9 42]
  [23 75 44]]

 [[22  1 80]
  [12 84 26]
  [19 10 90]
  [37 78 28]
  [87 61 71]
  [33 63 13]]]


Numpy also allow to reshape to acommodate the elements.

One can simply pass -1 as value for any one dimension and Numpy will estimate the correct value

In [ ]:

print('One dimensional A \n',oneD_A)
# The following is to show that if it can't reshape, it throw and Error
#arr = oneD_A.reshape(5,-1)
#
arr = oneD_A.reshape(4,-1)
print('two D \n', arr)
arr = oneD_A.reshape(3,-1,2)
print('three D \n', arr)

One dimensional A 
 [[21 68 40 51 85 82 80 62 32 69 76 51 59  9 42 23 75 44 22  1 80 12 84 26
  19 10 90 37 78 28 87 61 71 33 63 13]]
two D 
 [[21 68 40 51 85 82 80 62 32]
 [69 76 51 59  9 42 23 75 44]
 [22  1 80 12 84 26 19 10 90]
 [37 78 28 87 61 71 33 63 13]]
three D 
 [[[21 68]
  [40 51]
  [85 82]
  [80 62]
  [32 69]
  [76 51]]

 [[59  9]
  [42 23]
  [75 44]
  [22  1]
  [80 12]
  [84 26]]

 [[19 10]
  [90 37]
  [78 28]
  [87 61]
  [71 33]
  [63 13]]]


#Resizing
In some cases, one might be working with arrays with different dimensions and then one need to resize one of them.   

At that instant, **np.resize()** function returns new array with specified shape

* if one passes array and the new array is larger than original array, then new array is filled with copies of the original array (repeated as per the requirement)

In [ ]:
print('One dimensional A \n',oneD_A)
print(oneD_A.shape)

arr = oneD_A.reshape(4,9)
print('\n\n arr shape ',arr.shape)
print('\n arr \n ', arr)
arr1=np.resize(arr,[4,6])
print('\n arr reduced to 4 x 6\n ', arr1)
arr2=np.resize(arr,[8,4])
print('\n arr increased to 8 x 4\n ', arr2)


One dimensional A 
 [[21 68 40 51 85 82 80 62 32 69 76 51 59  9 42 23 75 44 22  1 80 12 84 26
  19 10 90 37 78 28 87 61 71 33 63 13]]
(1, 36)


 arr shape  (4, 9)

 arr 
  [[21 68 40 51 85 82 80 62 32]
 [69 76 51 59  9 42 23 75 44]
 [22  1 80 12 84 26 19 10 90]
 [37 78 28 87 61 71 33 63 13]]

 arr reduced to 4 x 6
  [[21 68 40 51 85 82]
 [80 62 32 69 76 51]
 [59  9 42 23 75 44]
 [22  1 80 12 84 26]]

 arr increased to 8 x 4
  [[21 68 40 51]
 [85 82 80 62]
 [32 69 76 51]
 [59  9 42 23]
 [75 44 22  1]
 [80 12 84 26]
 [19 10 90 37]
 [78 28 87 61]]


# Array concatentation and splitting
Combine multiple arrays into a single array and also split a single array into multiple arrays

*Joining Array*

**np.concatenate()** take atuple or list of arrays to be concatenated as its first srgument.
* One can join two or more arrays together using this method.
* Remember that while joining two arrays, the number of dimensions needs to be the same.



In [ ]:
#Concatenating two arrays
arr1 = np.array([1,2,3,4])
arr2 = np.array([11,12,13,14,15,16])
arr3=np.concatenate([arr1,arr2])
print("arr1  ", arr1)
print("arr2 ", arr2)
print("The joined list of arr1, arr2  ", arr3)

arr1   [1 2 3 4]
arr2  [11 12 13 14 15 16]
The joined list of arr1, arr2   [ 1  2  3  4 11 12 13 14 15 16]


In [ ]:
arr4 = np.concatenate([arr1,arr2,arr3,arr1])
print(' arr4', arr4)

 arr4 [ 1  2  3  4 11 12 13 14 15 16  1  2  3  4 11 12 13 14 15 16  1  2  3  4]


**two D rowwise addition**

In [ ]:
arr1 = np.array([[1,2,3,4,5,6],[11,12,13,14,15,16]])
arr2 = np.array([[21,22,23,24,25,26],[31,32,33,34,35,36],[41,42,43,44,45,46]])
arr3=np.concatenate([arr1,arr2])
print('arr1 \n', arr1)
print('arr2 \n', arr2)
print('arr3 \n', arr3)

arr1 
 [[ 1  2  3  4  5  6]
 [11 12 13 14 15 16]]
arr2 
 [[21 22 23 24 25 26]
 [31 32 33 34 35 36]
 [41 42 43 44 45 46]]
arr3 
 [[ 1  2  3  4  5  6]
 [11 12 13 14 15 16]
 [21 22 23 24 25 26]
 [31 32 33 34 35 36]
 [41 42 43 44 45 46]]


**two D columnwise addition**

In [ ]:
arr1 = np.array([[1,2,3,4,5,6,7],[11,12,13,14,15,16,17]])
arr2 = np.array([[21,22,23,24,25,26],[31,32,33,34,35,36]])
arr3=np.concatenate([arr1,arr2], axis=1)
print('arr1 \n', arr1)
print('arr2 \n', arr2)
print('arr3 \n', arr3)

arr1 
 [[ 1  2  3  4  5  6  7]
 [11 12 13 14 15 16 17]]
arr2 
 [[21 22 23 24 25 26]
 [31 32 33 34 35 36]]
arr3 
 [[ 1  2  3  4  5  6  7 21 22 23 24 25 26]
 [11 12 13 14 15 16 17 31 32 33 34 35 36]]


**np.vstack(), np.hstack(), np.dstack()**  usage

When two arrays to be concatenated are of different dimensions, then it is better to use np.vstack() (vertical stack)

In [ ]:
arr1 = np.array([[1,2,3,4,5,6],[11,12,13,14,15,16]])
arr2 = np.array([[21,22,23,24,25,26],[31,32,33,34,35,36],[41,42,43,44,45,46]])
arr3=np.vstack([arr1,arr2])
print('arr1 \n', arr1)
print('arr2 \n', arr2)
print('arr3 \n', arr3)

arr1 
 [[ 1  2  3  4  5  6]
 [11 12 13 14 15 16]]
arr2 
 [[21 22 23 24 25 26]
 [31 32 33 34 35 36]
 [41 42 43 44 45 46]]
arr3 
 [[ 1  2  3  4  5  6]
 [11 12 13 14 15 16]
 [21 22 23 24 25 26]
 [31 32 33 34 35 36]
 [41 42 43 44 45 46]]


 np.hstack() (horizontal stack).



In [ ]:
arr1 = np.array([[1,2,3,4,5,6,7],[11,12,13,14,15,16,17]])
arr2 = np.array([[21,22,23,24,25,26],[31,32,33,34,35,36]])
arr3=np.hstack([arr1,arr2])
print('arr1 \n', arr1)
print('arr2 \n', arr2)
print('arr3 \n', arr3)

arr1 
 [[ 1  2  3  4  5  6  7]
 [11 12 13 14 15 16 17]]
arr2 
 [[21 22 23 24 25 26]
 [31 32 33 34 35 36]]
arr3 
 [[ 1  2  3  4  5  6  7 21 22 23 24 25 26]
 [11 12 13 14 15 16 17 31 32 33 34 35 36]]


np.stack() : stack arrays along the third axis

In [ ]:
arr1 = np.array([[1,2,3,4,5,6],[11,12,13,14,15,16]])
arr2 = np.array([[21,22,23,24,25,26],[31,32,33,34,35,36]])
arr3=np.dstack([arr1,arr2])   # combine array index by index and store like a stack
arr4=np.concatenate([arr1,arr2])

print('arr1 shape', arr3.shape)
print('arr1 \n', arr1)
print('arr1 shape', arr3.shape)
print('arr2 \n', arr2)
print('arr3 shape', arr3.shape)
print('arr3 \n', arr3)
print('arr4 shape', arr4.shape)
print('arr4 \n', arr4)

arr1 shape (2, 6, 2)
arr1 
 [[ 1  2  3  4  5  6]
 [11 12 13 14 15 16]]
arr1 shape (2, 6, 2)
arr2 
 [[21 22 23 24 25 26]
 [31 32 33 34 35 36]]
arr3 shape (2, 6, 2)
arr3 
 [[[ 1 21]
  [ 2 22]
  [ 3 23]
  [ 4 24]
  [ 5 25]
  [ 6 26]]

 [[11 31]
  [12 32]
  [13 33]
  [14 34]
  [15 35]
  [16 36]]]
arr4 shape (4, 6)
arr4 
 [[ 1  2  3  4  5  6]
 [11 12 13 14 15 16]
 [21 22 23 24 25 26]
 [31 32 33 34 35 36]]


# Mathematical operations on numpy arrays
One can perform mathematical operations like +,-,*,/... to two or more arrays.

Along with this numpy also has functions like *np.add()*, *np.subtract(), np.multiply(), np.divide(), np.remainder()*


---

**a.sum()**   Array-wise sum

**a.min()** Array-wise minimum value

**a.max(axis=0)** Maximum value of an array row

**a.max(axis=1)** Maximum value of an array column

**a.mean()** Mean

**a.median()** Median

**a.corrcoef()** Correlation coefficient

**np.std(a)** standard deviation

---

 > One compare two array elements using **==, >** and **<** operators

 > have these functions **np.exp(), np.sqrt(), np.log(), np.sin(), np.cos(), ...**

 > Logical operations on arrays with **np.logical_or(), np.logical_and(),np.logical_not()**
 ---


In [ ]:
A= np.array([10,20,30,40,50])
B= np.arange(5)
print('A : ', A , ' and B: ', B)
C= A+ B
print('C : ',C)
Cc = np.add(A,B)
print('Cc = np.add(A,B) ', Cc)
E = A+ B+C
Ee = np.add(A,B,C)
print('E = A+ B+C', E)
print('Ee = np.add(A,B,C)', Ee)
print( "Remember ")
print("np.add(A, B, C) is not the same as A + B + C. \n It modifies C in-place to be the result of A + B. ")
print( " --- "*10)
D= A- B
print(D)
print('Mean of A ', np.mean(A))
print('Max of A ', np.max(A))
print('Min of A ', np.min(A))
print('Standard deviation of A ', np.std(A))


A :  [10 20 30 40 50]  and B:  [0 1 2 3 4]
C :  [10 21 32 43 54]
Cc = np.add(A,B)  [10 21 32 43 54]
E = A+ B+C [ 20  42  64  86 108]
Ee = np.add(A,B,C) [10 21 32 43 54]
Remember 
np.add(A, B, C) is not the same as A + B + C. 
 It modifies C in-place to be the result of A + B. 
 ---  ---  ---  ---  ---  ---  ---  ---  ---  --- 
[10 19 28 37 46]
Mean of A  30.0
Max of A  50
Min of A  10
Standard deviation of A  14.142135623730951


# Transposing arrays
 Transponse of the matrix

 **np.transpose(Array)**

 **Array.T**

In [ ]:
twoD_A = np.random.randint(low=0,high=100,size=(6,6))
print(twoD_A)

print("Transposed Array \n", np.transpose(twoD_A))
print('\n ----\n\n')
print("Transposed Array \n", twoD_A.T)


[[81 54 74  1  9 52]
 [27 65 25 41 76 22]
 [73 98 25  5 55 89]
 [79 11 40 81 65 54]
 [53  1 69 44 50 16]
 [ 5 28 55 61 86 82]]
Transposed Array 
 [[81 27 73 79 53  5]
 [54 65 98 11  1 28]
 [74 25 25 40 69 55]
 [ 1 41  5 81 44 61]
 [ 9 76 55 65 50 86]
 [52 22 89 54 16 82]]

 ----


Transposed Array 
 [[81 27 73 79 53  5]
 [54 65 98 11  1 28]
 [74 25 25 40 69 55]
 [ 1 41  5 81 44 61]
 [ 9 76 55 65 50 86]
 [52 22 89 54 16 82]]


#Inserting and deleting array elements

**numpy.insert(arr, obj, values, axis=None)**

where

**arr** is the Input array

**obj** specifies the index or indices before which insertion is to be made

**values** is the array of values to be inserted

**axis** denotes the axis along which values have to be inserted


In [ ]:

x = np.array([[0,0], [1,1], [2,2]])
print(x)

y= np.insert(x, 2,14)

print("\n y \n ",y)

yy= np.insert(x, 3,14)

print("\n yy \n ",yy)

z=np.insert(x, 2, [12,13,14], axis=1)

print("\n z\n", z)

az=np.insert(x, 1, 13, axis=1)

print("\n az \n", az)


[[0 0]
 [1 1]
 [2 2]]

 y 
  [ 0  0 14  1  1  2  2]

 yy 
  [ 0  0  1 14  1  2  2]

 z
 [[ 0  0 12]
 [ 1  1 13]
 [ 2  2 14]]

 az 
 [[ 0 13  0]
 [ 1 13  1]
 [ 2 13  2]]


deleting values from an array
**numpy.delete(arr, obj, axis)**

**arr** : [ array_like ]  Input array.

**obj** : [int, array of ints.] Sub-array to delete

**axis** : Axis along which we want to delete sub-arrays.



In [ ]:
x = np.array([[0,1,2,3], [10,11,12,13], [20,21,22,23]])
print(x)

obj =2
y= np.delete(x, obj)
print('\n -- y obj =2 -- \n')
print(y)

obj=[0,3]
y=np.delete(x,obj)
print("\n- y obj = [0,3] -\n")
print(y)


y=np.delete(x,1,1)
print("\n y=np.delete(x,1,1)-\n")
print(y)
y=np.delete(x,2,1)
print("\n  y=np.delete(x,2,1) -\n")
print(y)

y=np.delete(x,1,0)
print("\n y=np.delete(x,1,0)-\n")
print(y)
y=np.delete(x,2,0)
print("\n  y=np.delete(x,2,0) -\n")
print(y)




[[ 0  1  2  3]
 [10 11 12 13]
 [20 21 22 23]]

 -- y obj =2 -- 

[ 0  1  3 10 11 12 13 20 21 22 23]

- y obj = [0,3] -

[ 1  2 10 11 12 13 20 21 22 23]

 y=np.delete(x,1,1)-

[[ 0  2  3]
 [10 12 13]
 [20 22 23]]

  y=np.delete(x,2,1) -

[[ 0  1  3]
 [10 11 13]
 [20 21 23]]

 y=np.delete(x,1,0)-

[[ 0  1  2  3]
 [20 21 22 23]]

  y=np.delete(x,2,0) -

[[ 0  1  2  3]
 [10 11 12 13]]


#Find the index of a value



In [ ]:
x = np.array([[0,1,2,3], [10,11,12,13], [20,21,22,23]])
print(x)
index = np.where(x==13)
print("Index of value 12 is" , index[0], ' : ', index[1])

[[ 0  1  2  3]
 [10 11 12 13]
 [20 21 22 23]]
Index of value 12 is [1]  :  [3]


In [ ]:
x = np.array([[0,1,2,3], [10,11,12,13], [13,21,22,23]])
print(x)
index = np.where(x==13)
print("Index of value 12 is" , index)

[[ 0  1  2  3]
 [10 11 12 13]
 [13 21 22 23]]
Index of value 12 is (array([1, 2]), array([3, 0]))


Check if the numpy array is empty
size() returns the total number of elements in the array, and can be used to check if array has values or is empty

In [ ]:
if (x.size ==0 ):
  print("Given array is empty")
else:
  print("Array is ", x)
  print("\nLength of Array is ", x.size)

Array is  [[ 0  1  2  3]
 [10 11 12 13]
 [13 21 22 23]]

Length of Array is  12


# Sorting a numpy array

**numpy.sort(array, axis=-1, kind='quicksort", order=None)**

**array** is  the numpy aray that has to be sorted

**axis** is the axis along which the array will be sorted

**kind** specifies sorting algorithm: *mergesort*, *heapsort*, *stable*, *quicksort*

**order** can be singe column name

In [ ]:
dtype = [('name', 'S10'), ('height', float), ('age', int)]
Values = [('Arthur A', 1.8, 41), ('Arthur B', 1.9, 33), ('Arthur C', 1.7, 38),('Arthur D', 1.3, 36), ('Arthur E', 1.3, 38)]
a = np.array(Values,  dtype=dtype)
print(a)
print("\n --- \n")
np.sort(a, order='age')

[(b'Arthur A', 1.8, 41) (b'Arthur B', 1.9, 33) (b'Arthur C', 1.7, 38)
 (b'Arthur D', 1.3, 36) (b'Arthur E', 1.3, 38)]

 --- 



array([(b'Arthur B', 1.9, 33), (b'Arthur D', 1.3, 36),
       (b'Arthur C', 1.7, 38), (b'Arthur E', 1.3, 38),
       (b'Arthur A', 1.8, 41)],
      dtype=[('name', 'S10'), ('height', '<f8'), ('age', '<i8')])

# Normalize array

Normalizing an array is the process of bringing the array values to some defined range.

We can normalize an array so that its value vary from 0 to 1.

$x = \frac{x- x_{min}}{x_{max} - x_{min}}$

    

In [ ]:
arr=np.array([-12311,123, 1231, 441,421,4242,123,41312,4242,122,341,341,1234,122343])
print(' Before normalization \n :', arr)
arr_max = arr.max()
arr_min = arr.min()
arrN= (arr- arr_min)/(arr_max-arr_min)
print(' Before normalization \n :', arrN)


 Before normalization 
 : [-12311    123   1231    441    421   4242    123  41312   4242    122
    341    341   1234 122343]
 Before normalization 
 : [0.         0.09234037 0.10056887 0.09470198 0.09455345 0.12292988
 0.09234037 0.39822805 0.12292988 0.09233294 0.09395933 0.09395933
 0.10059114 1.        ]


#Array Subsets

One can easily create one or more subsets of numpy array. These subsets will also be numpy array objects.

One should be careful to have copy.

One can do following
* Create a subsetof array that has only diagonal elements from original array.
* Create a subset having a dimension omitted if there is only one element in tha dimensions
* Subset created on boolean conditions.
* Based on the array of indices.

Some of the methods are **choose(), diagonal(), take(), ...**



In [ ]:
arr = np.array([[1,2,3,4],[11,12,13,14],[21,22,23,24],[31,32,33,34]])
print(arr)

##  row 2, row 3, row 1, row 0
print('\n np.choose([2,3,1,0], arr) ')
newarr= np.choose([2,3,1,0], arr)
print(newarr)


print('\n newarr2= np.choose([2,4,1,0], arr, mode=\'clip\'') # 4 goes to 3 (4-1)')
newarr2= np.choose([2,4,1,0], arr, mode='clip') # 4 goes to 3 (4-1)
print(newarr2)

print('\n newarr2= np.choose([2,5,5,0], arr, mode=\'clip\'') # 5 get clipped  to 3')
newarr22= np.choose([2,5,5,0], arr, mode='clip') # 5 gets clipped to 3
print(newarr22)

#'wrap' mode will use your indices modulo the length of the array
print('\n newarr3= np.choose([2,4,1,0], arr, mode=\'wrap\'') # 4 goes to (4 mod 4)')
newarr3= np.choose([2,4,1,0], arr, mode='wrap') # 4 goes to (4 mod 4)
print(newarr3)
print('\n newarr3= np.choose([2,5,1,0], arr, mode=\'wrap\'') # 5 goes to (5 mod 4)')
newarr3= np.choose([2,5,1,0], arr, mode='wrap') # 5 goes to (5 mod 4)
print(newarr3)


[[ 1  2  3  4]
 [11 12 13 14]
 [21 22 23 24]
 [31 32 33 34]]

 np.choose([2,3,1,0], arr) 
[21 32 13  4]

 newarr2= np.choose([2,4,1,0], arr, mode='clip'
[21 32 13  4]

 newarr2= np.choose([2,5,5,0], arr, mode='clip'
[21 32 33  4]

 newarr3= np.choose([2,4,1,0], arr, mode='wrap'
[21  2 13  4]

 newarr3= np.choose([2,5,1,0], arr, mode='wrap'
[21 12 13  4]


In [ ]:
arr = np.array([[1,2,3,4],[11,12,13,14],[21,22,23,24],[31,32,33,34]])
print(arr)
print('Diagonal')
dia = arr.diagonal()
print(dia)

print(' \n  ----- \n')
arr3D = np.arange(27).reshape(3,3,3)
print(arr3D)
print('Diagonal')
print(arr3D.diagonal(axis1=1, axis2=2))


[[ 1  2  3  4]
 [11 12 13 14]
 [21 22 23 24]
 [31 32 33 34]]
Diagonal
[ 1 12 23 34]
 
  ----- 

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]
Diagonal
[[ 0  4  8]
 [ 9 13 17]
 [18 22 26]]


In [ ]:
arr3D = np.random.rand(3,3,3)
print(arr3D)
print(' \n ----\n')
a=np.take(arr3D, [[2,1,2],[4,6,10]])
print(a)

[[[0.46032528 0.82045249 0.63389493]
  [0.0894249  0.59895182 0.65901307]
  [0.02318286 0.66925952 0.9867747 ]]

 [[0.1514769  0.98292622 0.35418236]
  [0.71725376 0.42926917 0.48207629]
  [0.19742643 0.52771312 0.24778576]]

 [[0.27644926 0.03849887 0.8658224 ]
  [0.52853124 0.90215474 0.55343812]
  [0.34734564 0.27360725 0.68204355]]]
 
 ----

[[0.63389493 0.82045249 0.63389493]
 [0.59895182 0.02318286 0.98292622]]


There is lot of more functionality of Numpy. But we will stop here.
--
One can play with this notebook and modify and see what changes one get.
--

---